ens_jobeet_ens_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

ens_jobeet_homepage:
    pattern: /
    defaults: { _controller: EnsJobeetBundle:Job:index }

ens_jobeet_category:
    pattern: /category/{slug}
    defaults: {_controller: EnsJobeetBundle:Category:show}