login:
    pattern:   /login
    defaults:  { _controller: EnsJobeetBundle:Default:login }
    
login_check:
    pattern:   /login_check
    
ens_jobeet_ens_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

ens_jobeet_homepage:
    pattern: /
    defaults: { _controller: EnsJobeetBundle:Job:index }

ens_jobeet_category:
    pattern: /category/{slug}/{page}
    defaults: {_controller: EnsJobeetBundle:Category:show, page: 1 }

logout:
    pattern: /logout
    
ens_jobeet_api:
    pattern: /api/{token}/jobs.{_format}
    defaults: {_controller: "EnsJobeetBundle:Api:list"}
    requirements:
      _format: xml|json|yaml
      
EnsobeetBundle_ibw_affiliate:
    resource: "@EnsJobeetBundle/Resources/config/routing/affiliate.yml"
    prefix:   /affiliate