Ens\JobeetBundle\Entity\Job:
  properties:
    email:
      - NotBlank: ~
      - Email: ~
    type:
      - NotBlank: ~
      - Choice: { callback: getTypesValues }
    company:
      - NotBlank: ~
    position:
      - NotBlank: ~
    location:
      - NotBlank: ~
    description:
      - NotBlank: ~
    how_to_apply:
      - NotBlank: ~
    email:
      - NotBlank: ~
      - Email: ~
    url:
      - Url: ~
    file:
      - Image: ~
      
Ens\JobeetBundle\Entity\Affiliate:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraint\UniqueEntity: email
  properties:
    url:
      - Url: ~
    email:
      - NotBlank: ~
      - Email: ~
     