Ens\JobeetBundle\Entity\Job:
  properties:
    email:
      - NotBlank: ~
      - Email: ~
    type:
      - NotBlank: ~
      - Choice: { callback: getTypeValues }
    company:
      - NotBlank: ~
    position:
      - NotBlank: ~
    location:
      - NotBlank: ~
    description:
      - NotBlank: ~
    how_to_apply:
      - NotBlank: ~
    email:
      - NotBlank: ~
      - Email: ~
    url:
      - Url: ~
    file:
      - Image: ~
 